---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: testflux
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 5m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/AAkindele/testflux.git

