apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}-memory
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}-memory
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.name}}-memory
  template:
    metadata:
      labels:
        app: {{gitops.name}}-memory
        version: beta-{{gitops.version}}
        deploy: {{gitops.deploy}}
        test: test1
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          args:
          - --in-memory
          - --prometheus
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-memory
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}-memory

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{gitops.name}}-memory
  namespace: {{gitops.namespace}}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ngsa-memory.loblaws.cseretail.com`)
      kind: Rule
      services:
        - name: {{gitops.name}}-memory
          kind: Service
          port: 8080
