apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: overlay-a
spec:
  interval: 5m
  prune: true
  path: ./overlay-a
  sourceRef:
    kind: GitRepository
    name: testflux
    namespace: flux-system
  postBuild:
    substitute:
      REPLACE_ME: "world"
