apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp2
    image: hello-world:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
